apiVersion: apps/v1
kind: Deployment
metadata:
  name: headersnbody
  namespace: diagnostics
spec:
  selector:
    matchLabels:
      app: headersnbody
  template:
    metadata:
      labels:
        app: headersnbody
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: headersnbody
        image: hiprabhat/headersnbody:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: headersnbody
  namespace: ecommerce
  labels:
    app: headersnbody
spec:
  selector:
    app: headersnbody
  ports:
  - port: 80
    targetPort: 8080
    name: http-headersnbody
